development:
  database: http://localhost:5984/coworkers_development
  validation_framework: :active_model
test:
  database: coworkers_test
  validation_framework: :active_model
production:
  validation_framework: :active_model
  database: <%= ENV['CLOUDANT_URL'] %>/coworkers_production
