development:
  adapter: postgresql
  encoding: unicode
  database: cobot_coworkers_development
  pool: 5
  timeout: 5000
  port: 5432
  host: 127.0.0.1
test: &test
  adapter: postgresql
  encoding: unicode
  database: cobot_coworkers_test
  pool: 5
  timeout: 5000
  port: 5432
  host: 127.0.0.1
